= 一个人在家时II游戏攻略
Muir Mok <muirmok@gmail.com>
:author: Muir Mok
:toc:
:imagesdir: images
:encoding: utf-8

本攻略以https://store.steampowered.com/app/1120360/At_Home_Alone_II/[Steam版]为准。
与剧情有关的部分用鼠标选择反白就能看到。

== 操作说明

|===
|按键|效果

|*↑←↓→*
|移动

|*Z*
|确认/调查

|*X*
|取消/后退

|*Shift*
|加速移动（游戏后期可用）

|*Esc/X*
|菜单

|*Ctrl*
|加速对话

|*F5*
|全屏切换

|*F7*
|窗口大小调整
|===

== 攻略

=== 第一次循环

开始以后，出门到外面和小男孩对话。

到一楼厨房调查冰箱，到客厅和小男孩对话。

出门到外面和大哥哥对话，进房间。

出门到外面和黄色头发小女孩对话，进房间。
出房间，和小女孩对话，选择 *让她离开* ，回到房间。
上二楼，前往阳台，触发剧情。

=== 第二次循环

选 *不跳过* 。 

出门到外面和小男孩对话。

到一楼厨房调查冰箱，到客厅和小男孩对话。

出门到外面和大哥哥对话，进房间。

和大哥哥对话中选择 *一起上去看看* 。

到二楼和大哥哥对话，回到一楼厨房拿 *备份钥匙* 。

回到二楼和大哥哥对话，触发剧情。

=== 第三次循环

选 *不跳过* 。

出门到外面和小男孩对话。

到一楼厨房调查冰箱，到客厅和小男孩对话。

和小男孩对话中，选择 *吃完我们去玩吧* ，前往后院，触发剧情。

调查二楼自己卧室的门，再到一楼厨房拿 *枪* 。

回到二楼，触发剧情。

前往阳台，触发剧情。

画面中出现重要提示，记录下 [white]#地面的数字：851216# 。

=== 第四次循环

重新开始游戏，选 *不跳过* 。

调查浴室的门和妈妈房间的门之间的墙壁正中间的部分。输入拿到的6位数字。

=== 第五次循环

前往二楼阳台，听到门铃，出门，出门到外面和小男孩对话。

到一楼厨房调查冰箱，到客厅和小男孩对话。

前往后院，触发剧情。

回到客厅，前往二楼自己卧室的门，再到一楼厨房拿 *枪* 。

回到二楼，前往阳台。

=== 第六次循环

重新开始游戏，与鬼魂对话，调查右方祭坛物品，再与鬼魂对话。
调查左侧灰色的门。

选 *不跳过* 。

出门到外面和小男孩对话。

到一楼厨房调查冰箱，到客厅和小男孩对话。

和小男孩对话中，选择 *吃完我们去玩吧* ，前往后院，触发剧情。

对话中选择2次 *交给它* 。

=== 精神世界

到房子外面和男子对话，对话中选择 *接受* 。

=== 结局1

进房间触发剧情，对话中选择 *开始画画* ，画完所有的画，触发剧情。

四次捉迷藏游戏中小女孩的躲藏地点：

. 房子大门外面右侧的草丛
. 二楼阳台的门后面
. 厨房桌子下
. 一楼大厅的红色沙发和盆栽的中间

=== 结局2

开始游戏，向上或向下移动，调查乌鸦。

到卧室调查白色椅子，选择 *拿起* 。
来到浴室，在镜子前选择 *其他* -> *砸掉镜子* 。
再调查破掉的镜子，选择 *爬进去* 。

在长廊中躲避小人的阻挡和追赶，进入大门。

=== 结局之后的剧情

开始游戏，向左或向右移动，调查白色椅子。

选择 *不跳过* 。

去后院，移动白色椅子到草丛中木板的破口处，选择 *爬上去* 。

