= 杀戮的天使游戏攻略
Mike Akiba <mike2718@gmail.com>
:author: Mike Akiba
:lang: zh-CN
:imagesdir: images
:encoding: utf-8

本攻略以 https://store.steampowered.com/app/537110/Angels_of_Death/[Steam版]为准。

与剧情有关的地方请用鼠标选择空白的地方就能看到。

== 操作说明

[options="header"]
|===
|按键|效果

|*↑↓←→*, *2、4、6、8* （数字键盘）
|移动

|*Shift*
|快跑

|*Z*, *Enter*, *Space*
|确定、对话、调查

|*X*, *Esc*, *0* （数字键盘）
|取消、显示菜单

|*Alt+Enter*
|切换窗口/全屏模式

|*Alt+F4*
|强制退出

|*F12*
|回主菜单

|*F1*
|游戏设置
|===

== Episode 1

=== 最底层

出门后调查墙上的字迹，调查电脑房内中央的镜子，再调查电脑。

调查电脑旁的机器，得到**钥匙卡**。

调查铁栅栏门左侧的装置，从菜单中选择使用道具钥匙卡。

调查电梯门。

=== Floor B6

调查左侧电梯通道的门，进入传单旁的暗巷，调查洞拿到**B6室内的钥匙**。

用钥匙打开右下方B6室的门，进入左边房间从大箱子里拿到**一袋零食**。

进入左侧暗巷，调查天花板的洞里的小鸟，把零食给小鸟，拿到**受伤的小鸟**。

走出暗巷，调查3次小鸟，触发剧情。

跑到B6室的左侧房间，[white]#藏到大箱子里面#。

进入左侧的门，再从上面的门出去。

调查小鸟，再调查下方黄色泥土处的铲子，拿到**EV通道管理室的钥匙**。

调查出来的房间的上锁的门，使用钥匙。进入通道，调查开关，选择**按下按钮**。

调查电梯通道的门，进入电梯。

=== Floor B5

调查左侧的门，再到诊疗室的椅子上拿到**住院楼走廊的钥匙**。

对铁栅栏门使用钥匙，打开门。

调查左边第一间病房墙壁上的字迹，再调查铁栅栏门。

调查六个格子的柜子，把三种颜色的义眼拿给医生，从丹尼医生那里拿到**柜子的钥匙**。

调查六个格子的柜子。

调查出口，再调查刚才医生呆过的地方，拿到**撬棍**。

对出口使用撬棍。

前往电梯门，前往医生尸体的房间，调查医生尸体，选择**触摸口袋**，获得**EV管理室的钥匙**。

使用钥匙进入EV管理室，按下按钮，返回电梯门，调查电梯门。

=== Floor B4

调查第2墓地的墓穴，选择**伸出手**，拿到**保管室的钥匙**。

使用钥匙打开保管室的门，调查右侧冷冻库，调查墙壁上的洞，

调查有水流出的地方，拿到**第1墓地的钥匙**。

使用钥匙打开第1墓地的门，调查最上方的墓碑。

调查墙上的裂缝，选择**进去**。

调查左侧箱子，拿到**手电筒**。

调查桌子上的设计图。

返回入口，与扎克对话，再次进入裂缝，调查设计图。

==== 札克视角

调查第2墓地的墓穴旁边的镐子，拿到**十字镐**。

调查第1墓地的奇形怪状的岩石，选择**破坏墓碑**。

调查并破坏第1墓地和第2墓地的所有墓碑和石碑。

调查第1墓地左上方第三个被破坏的墓碑处。

==== 瑞依视角

进入深处的门，选择道具手电筒。

调查桌子上的履历表的纸，调查最右侧的圆形机关。

返回到扎克的地方。

调查第1墓地出口处的小纸条、第2墓地上方道路处的小纸条、电梯门房间的小纸条。

调查电梯门房间的水底的凸起处。

进入第1墓地的裂缝，调查地面上的小纸条，

进入深处房间，使用手电筒，调查地面上的小纸条，调查最右侧的圆形机关。

==== 札克视角

调查第1墓地的裂缝。

==== 瑞依视角

调查水温的温度计，再调查调节水温的控制杆。

==== 札克视角

在保管室调查墙上的裂缝。

==== 瑞依视角

进入下面的门，进入迷宫，调查电源。

与札克对话，调查电梯的开关。调查电梯门。

== Episode 2

== Episode 3

== Episode 4

