= 学习ed行编辑器
Muir Mok <muirmok@gmail.com>
:author: Muir Mok
:imagesdir: images
:encoding: utf-8
:lang: zh-CN

== 基础知识

ed是一种基于行的编辑器。在大多数类Unix系统上可以找到。
它的存在影响了后来的ex、vi编辑器和sed。

它是最早开发出来的Unix系统组件之一。由于当时的输入设备是简陋的终端机，这导致了它的设计相当简洁，这也使得它对于初学者有一定难度。

== 进入和退出

本教程使用GNU ed 1.10作为示范，以下所有命令在Ubuntu 18.04系统上运行。

要进入ed编辑器，在终端输入 `ed` 回车；要退出ed，输入 `q` 回车。

----
$ ed
q
----

== 写入新的行

不像nano，gedit等编辑器那样，在打开的ed上，立即输入一连串的字符串不会被“记录”下来，我们必须先敲入命令，才能进行输入，输入结束后，还要输入结束的命令。

输入 `ed` 回车，输入 `a` 回车，再输入 `first line` 回车，最后输入 `.` 回车。

----
$ ed
a
first line
.
----

这里，输入的 `a` 命令是让我们进入了ed的插入模式，在插入模式下，我们才可以进行键盘输入。输入的 `.` 表示我们的输入已经完成。

即使现在画面上没有什么新的变化，我们在ed上确实输入了内容。

== 列出行

输入 `n` 回车。

----
n
1       first line
----

`n` 命令用于列出行的内容。我们看到首先显示了数字1，表示目前显示的是第一行的内容，紧跟若干个空格，就是刚才我们输入的first line。

TIP: `n` 默认显示行号。如果不需要行号，输入 `p` 。

== 插入行

输入 `i` 回车，输入 `hello ed` 回车，最后输入 `.` 回车。

----
i
hello ed
.
----

`i` 的作用是在上一行输入内容，通过列出整个文件的内容，可以看到我们确实在原来的first line的上方插入了hello ed。

TIP: `i` 是向上插入行， `a` 是向下插入行。

== 列出所有行

接下来我们来看看整个文件的内容，输入 `1,$n`

----
1,$n
1       hello ed
2       first line
----

`1,$n` 的作用是列出文件从第一行到最后一行的内容， `1,$` 表示指定从第一行到最后一行的范围，这种指定范围的办法也可以用在其它命令上。

可以看到我们确实输入了内容，hello ed位于第一行，first line位于第二行。

== 修改行

我们现在来修改第二行的内容，输入 `2c` 回车，再输入 `second line` 回车， 最后输入 `.` 回车。

----
2c
second line
.
----

`2c` 表示“修改第二行的内容”，ed每次只能修改一行，其中数字2指定了要修改的行数，c是修改的命令。

再来看看文件现在的内容，输入 `1,$n`

----
1,$n
1       hello ed
2       second line
----

可以看到文件的第二行被我们修改了，first没有了，改成了second。

== 保存文件

最后我们执行 `w text` 命令，将文件保存到一个名为text的文件中。
保存完成后，ed输出了 `21` ，表示写入了总共 `21` 个字符。

----
w text
21
q
----

`w` 是“保存”的命令。 `w file` 表示将目前的内容保存到一个名字叫做 `file` 的文件中。

== 删除行

== 执行外部命令

`!` 后面跟命令，可以将外部命令的输出显示在ed中。

----
$ ed
!date
Thu Feb 13 04:26:34 CST 2020
!
----

== 命令行选项

以下是GNU ed可用的命令行选项：

----
用法： ed [选项] [文件]

选项：
  -h，--help                 显示此帮助并退出
  -V，--version              输出版本信息并退出
  -G，--traditional          使用兼容模式运行
  -l，--loose-exit-status    即使命令失败，也以状态 0 退出
  -p，--prompt=STRING        使用 STRING 作为交互提示符
  -r，--restricted           以受限模式运行
  -s，--quiet                静默模式
  -v，--verbose              输出详细内容
----
